### ISSUE TITLE
Nashorn Engine removed as of Java 15

### ISSUE THREAD

**Issue by HandyHat** [zDevelopers/QuartzLib#69] opened 2020-12-14 15:43 UTC
I was testing running my server with Java 11, and the following warning is outputted while ImageOnMap is enabling:
`[Server thread/WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[Server thread/WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[Server thread/WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[Server thread/WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release`

It looks like Nashorn Engine has indeed been removed as of Java 15, and so ImageOnMap should be updated to ensure it can continue to be used with Java versions 15 and up.

**Comment by Vlammar** [comment] 2020-12-14 17:00
This issue was moved because it's related to quartzLib and not only with IoM, thanks for the reminder. We will see to prepare update for java 15.

**Comment by HandyHat** [comment] 2020-12-14 17:17
Ah, I can see #31 already exists. Thanks!

**Comment by AmauryCarrade** [comment] 2020-12-26 11:36
Closing this one as a duplicate of #31. Thanks! We'll try to fix this soon so QuartzLib plugins work with Java 15+.

**Closed by AmauryCarrade** 2020-12-26 11:36 UTC
Labels: T ⋅ Dependencies
